$(document).ready(function()
{
	$("#li1").mouseenter(function()
	{
		$(this).css("font-size","25px");
		$(this).css("cursor","pointer");
	});
	$("#li1").mouseleave(function()
	{
		$(this).css("font-size","20px");
	});
	$("#li2").mouseenter(function()
	{
		$(this).css("font-size","25px");
		$(this).css("cursor","pointer");
	});
	$("#li2").mouseleave(function()
	{
		$(this).css("font-size","20px");
	});
	$("#li3").mouseenter(function()
	{
		$(this).css("font-size","25px");
		$(this).css("cursor","pointer");
	});
	$("#li3").mouseleave(function()
	{
		$(this).css("font-size","20px");
	});
	$("#li4").mouseenter(function()
	{
		$(this).css("font-size","25px");
		$(this).css("cursor","pointer");
	});
	$("#li4").mouseleave(function()
	{
		$(this).css("font-size","20px");
	});
	$("#li5").mouseenter(function()
	{
		$(this).css("font-size","25px");
		$(this).css("cursor","pointer");
	});
	$("#li5").mouseleave(function()
	{
		$(this).css("font-size","20px");
	});
	$("#li6").mouseenter(function()
	{
		$(this).css("font-size","25px");
		$(this).css("cursor","pointer");
	});
	$("#li6").mouseleave(function()
	{
		$(this).css("font-size","20px");
	});
	$("#li7").mouseenter(function()
	{
		$(this).css("font-size","25px");
		$(this).css("cursor","pointer");
	});
	$("#li7").mouseleave(function()
	{
		$(this).css("font-size","20px");
	});
	$("#li8").mouseenter(function()
	{
		$(this).css("font-size","25px");
		$(this).css("cursor","pointer");
	});
	$("#li8").mouseleave(function()
	{
		$(this).css("font-size","20px");
	});
	$("#li9").mouseenter(function()
	{
		$(this).css("font-size","25px");
		$(this).css("cursor","pointer");
	});
	$("#li9").mouseleave(function()
	{
		$(this).css("font-size","20px");
	});
	$("#li10").mouseenter(function()
	{
		$(this).css("font-size","25px");
		$(this).css("cursor","pointer");
	});
	$("#li10").mouseleave(function()
	{
		$(this).css("font-size","20px");
	});
	$("#li71").mouseenter(function()
	{
		$(this).css("font-size","25px");
		$(this).css("cursor","pointer");
	});
	$("#li71").mouseleave(function()
	{
		$(this).css("font-size","20px");
	});
	$("#li72").mouseenter(function()
	{
		$(this).css("font-size","25px");
		$(this).css("cursor","pointer");
	});
	$("#li72").mouseleave(function()
	{
		$(this).css("font-size","20px");
	});
	$("#li73").mouseenter(function()
	{
		$(this).css("font-size","25px");
		$(this).css("cursor","pointer");
	});
	$("#li73").mouseleave(function()
	{
		$(this).css("font-size","20px");
	});
	$("#li74").mouseenter(function()
	{
		$(this).css("font-size","25px");
		$(this).css("cursor","pointer");
	});
	$("#li74").mouseleave(function()
	{
		$(this).css("font-size","20px");
	});
	$("#li75").mouseenter(function()
	{
		$(this).css("font-size","25px");
		$(this).css("cursor","pointer");
	});
	$("#li75").mouseleave(function()
	{
		$(this).css("font-size","20px");
	});
    $("#li711").mouseenter(function()
	{
		$(this).css("font-size","25px");
		$(this).css("cursor","pointer");
	});
	$("#li711").mouseleave(function()
	{
		$(this).css("font-size","20px");
	});
	$("#li712").mouseenter(function()
	{
		$(this).css("font-size","25px");
		$(this).css("cursor","pointer");
	});
	$("#li712").mouseleave(function()
	{
		$(this).css("font-size","20px");
	});
	$("#li713").mouseenter(function()
	{
		$(this).css("font-size","25px");
		$(this).css("cursor","pointer");
	});
	$("#li713").mouseleave(function()
	{
		$(this).css("font-size","20px");
	});
	$("#li714").mouseenter(function()
	{
		$(this).css("font-size","25px");
		$(this).css("cursor","pointer");
	});
	$("#li714").mouseleave(function()
	{
		$(this).css("font-size","20px");
	});
	$("#li715").mouseenter(function()
	{
		$(this).css("font-size","25px");
		$(this).css("cursor","pointer");
	});
	$("#li715").mouseleave(function()
	{
		$(this).css("font-size","20px");
	});
	$("#li716").mouseenter(function()
	{
		$(this).css("font-size","25px");
		$(this).css("cursor","pointer");
	});
	$("#li716").mouseleave(function()
	{
		$(this).css("font-size","20px");
	});
	$("#li81").mouseenter(function()
	{
		$(this).css("font-size","25px");
		$(this).css("cursor","pointer");
	});
	$("#li81").mouseleave(function()
	{
		$(this).css("font-size","20px");
	});
	$("#li82").mouseenter(function()
	{
		$(this).css("font-size","25px");
		$(this).css("cursor","pointer");
	});
	$("#li82").mouseleave(function()
	{
		$(this).css("font-size","20px");
	});
	$("#li83").mouseenter(function()
	{
		$(this).css("font-size","25px");
		$(this).css("cursor","pointer");
	});
	$("#li83").mouseleave(function()
	{
		$(this).css("font-size","20px");
	});
	$("#li84").mouseenter(function()
	{
		$(this).css("font-size","25px");
		$(this).css("cursor","pointer");
	});
	$("#li84").mouseleave(function()
	{
		$(this).css("font-size","20px");
	});
	$("#li85").mouseenter(function()
	{
		$(this).css("font-size","25px");
		$(this).css("cursor","pointer");
	});
	$("#li85").mouseleave(function()
	{
		$(this).css("font-size","20px");
	});
	$("#li721").mouseenter(function()
	{
		$(this).css("font-size","25px");
		$(this).css("cursor","pointer");
	});
	$("#li721").mouseleave(function()
	{
		$(this).css("font-size","20px");
	});
	$("#li722").mouseenter(function()
	{
		$(this).css("font-size","25px");
		$(this).css("cursor","pointer");
	});
	$("#li722").mouseleave(function()
	{
		$(this).css("font-size","20px");
	});
	$("#li731").mouseenter(function()
	{
		$(this).css("font-size","25px");
		$(this).css("cursor","pointer");
	});
	$("#li731").mouseleave(function()
	{
		$(this).css("font-size","20px");
	});
	$("#li732").mouseenter(function()
	{
		$(this).css("font-size","25px");
		$(this).css("cursor","pointer");
	});
	$("#li732").mouseleave(function()
	{
		$(this).css("font-size","20px");
	});
	$("#li741").mouseenter(function()
	{
		$(this).css("font-size","25px");
		$(this).css("cursor","pointer");
	});
	$("#li741").mouseleave(function()
	{
		$(this).css("font-size","20px");
	});
	$("#li742").mouseenter(function()
	{
		$(this).css("font-size","25px");
		$(this).css("cursor","pointer");
	});
	$("#li742").mouseleave(function()
	{
		$(this).css("font-size","20px");
	});
	$("#li751").mouseenter(function()
	{
		$(this).css("font-size","25px");
		$(this).css("cursor","pointer");
	});
	$("#li751").mouseleave(function()
	{
		$(this).css("font-size","20px");
	});
	$("#li752").mouseenter(function()
	{
		$(this).css("font-size","25px");
		$(this).css("cursor","pointer");
	});
	$("#li752").mouseleave(function()
	{
		$(this).css("font-size","20px");
	});
	$("#li1").click(function()
	{
	   $("#forli1").show();
	   $("#forvis").css("padding", "0px");
	   $("#forvis").css("visibility", "hidden");
	   $("#forli2").hide();
	    $("#forli3").hide();
		 $("#forli4").hide();
		  $("#forli5").hide();
		  $("#forli6").hide();
	    $("#forli7").hide();
		 $("#forli8").hide();
		  $("#forli9").hide();
		   $("#forli10").hide();
	});
	$("#li1").dblclick(function()
	{
	   $("#forli1").hide();
	 $("#forvis").css("padding","200px");

	   /*$("#forvis").css("background-image","url("kids.jpg")");
	   $("#forvis").css("background-position","center");*/
	   $("#forli2").hide();
	    $("#forli3").hide();
		 $("#forli4").hide();
		  $("#forli5").hide();
		  $("#forli6").hide();
	    $("#forli7").hide();
		 $("#forli8").hide();
		  $("#forli9").hide();
		   $("#forli10").hide();
	});
	$("#li2").click(function()
	{
	   $("#forli2").show();
	   $("#forvis").css("padding", "0px");
	   $("#forvis").css("visibility", "hidden");
	   $("#forli1").hide();
	    $("#forli3").hide();
		 $("#forli4").hide();
		  $("#forli5").hide();
		  $("#forli6").hide();
	    $("#forli7").hide();
		 $("#forli8").hide();
		  $("#forli9").hide();
		   $("#forli10").hide();
	});
	$("#li2").dblclick(function()
	{
	   $("#forli2").hide();
	   $("#forvis").css("padding", "200px");
	   $("#forli1").hide();
	    $("#forli3").hide();
		 $("#forli4").hide();
		  $("#forli5").hide();
		  $("#forli6").hide();
	    $("#forli7").hide();
		 $("#forli8").hide();
		  $("#forli9").hide();
		   $("#forli10").hide();
	});
	$("#li3").click(function()
	{
	   $("#forli3").show();
	   $("#forvis").css("padding", "0px");
	   $("#forvis").css("visibility", "hidden");
	   $("#forli1").hide();
	    $("#forli2").hide();
		 $("#forli4").hide();
		  $("#forli5").hide();
		  $("#forli6").hide();
	    $("#forli7").hide();
		 $("#forli8").hide();
		  $("#forli9").hide();
		   $("#forli10").hide();
	});
	$("#li3").dblclick(function()
	{
	   $("#forli3").hide();
	   $("#forvis").css("padding", "200px");
	   $("#forli1").hide();
	    $("#forli2").hide();
		 $("#forli4").hide();
		  $("#forli5").hide();
		  $("#forli6").hide();
	    $("#forli7").hide();
		 $("#forli8").hide();
		  $("#forli9").hide();
		   $("#forli10").hide();
	});
	$("#li4").click(function()
	{
	   $("#forli4").show();
	   $("#forvis").css("padding", "0px");
	   $("#forvis").css("visibility", "hidden");
	   $("#forli1").hide();
	    $("#forli3").hide();
		 $("#forli2").hide();
		  $("#forli5").hide();
		  $("#forli6").hide();
	    $("#forli7").hide();
		 $("#forli8").hide();
		  $("#forli9").hide();
		   $("#forli10").hide();
	});
	$("#li4").dblclick(function()
	{
	   $("#forli4").hide();
	   $("#forvis").css("padding", "200px");
	   $("#forli1").hide();
	    $("#forli3").hide();
		 $("#forli2").hide();
		  $("#forli5").hide();
		  $("#forli6").hide();
	    $("#forli7").hide();
		 $("#forli8").hide();
		  $("#forli9").hide();
		   $("#forli10").hide();
	});
	$("#li5").click(function()
	{
	   $("#forli5").show();
	   $("#forvis").css("padding", "0px");
	   $("#forvis").css("visibility", "hidden");
	   $("#forli1").hide();
	    $("#forli3").hide();
		 $("#forli4").hide();
		  $("#forli2").hide();
		  $("#forli6").hide();
	    $("#forli7").hide();
		 $("#forli8").hide();
		  $("#forli9").hide();
		   $("#forli10").hide();
	});
	$("#li5").dblclick(function()
	{
	   $("#forli5").hide();
	   $("#forvis").css("padding", "200px");
	   $("#forli1").hide();
	    $("#forli3").hide();
		 $("#forli4").hide();
		  $("#forli2").hide();
		  $("#forli6").hide();
	    $("#forli7").hide();
		 $("#forli8").hide();
		  $("#forli9").hide();
		   $("#forli10").hide();
	});
	$("#li6").click(function()
	{
	   $("#forli6").show();
	   $("#forvis").css("padding", "0px");
	   $("#forvis").css("visibility", "hidden");
	    $("#forli1").hide();
	    $("#forli3").hide();
		 $("#forli4").hide();
		  $("#forli2").hide();
		  $("#forli5").hide();
	    $("#forli7").hide();
		 $("#forli8").hide();
		  $("#forli9").hide();
		   $("#forli10").hide();
	});
	$("#li6").dblclick(function()
	{
	   $("#forli6").hide();
	   $("#forvis").css("padding", "200px");
	    $("#forli1").hide();
	    $("#forli3").hide();
		 $("#forli4").hide();
		  $("#forli2").hide();
		  $("#forli5").hide();
	    $("#forli7").hide();
		 $("#forli8").hide();
		  $("#forli9").hide();
		   $("#forli10").hide();
	});
	$("#li7").click(function()
	{
	   $("#forli7").show();
	   $("#forvis").css("padding", "0px");
	   $("#forvis").css("visibility", "hidden");
	    $("#forli1").hide();
	    $("#forli3").hide();
		 $("#forli4").hide();
		  $("#forli2").hide();
		  $("#forli6").hide();
	    $("#forli5").hide();
		 $("#forli8").hide();
		  $("#forli9").hide();
		   $("#forli10").hide();
	});
	$("#li7").dblclick(function()
	{
	   $("#forli7").hide();
	   $("#forvis").css("padding", "200px");
	    $("#forli1").hide();
	    $("#forli3").hide();
		 $("#forli4").hide();
		  $("#forli2").hide();
		  $("#forli6").hide();
	    $("#forli5").hide();
		 $("#forli8").hide();
		  $("#forli9").hide();
		   $("#forli10").hide();
	});
	$("#li71").click(function()
	{
		$("#forli71").toggle();
		$("#forli72").hide();
		$("#forli73").hide();
		$("#forli74").hide();
		$("#forli75").hide();
	});
	$("#li72").click(function()
	{
		$("#forli72").toggle();
		$("#forli71").hide();
		$("#forli73").hide();
		$("#forli74").hide();
		$("#forli75").hide();
	});
	$("#li73").click(function()
	{
		$("#forli73").toggle();
		$("#forli72").hide();
		$("#forli71").hide();
		$("#forli74").hide();
		$("#forli75").hide();
	});
	$("#li74").click(function()
	{
		$("#forli74").toggle();
		$("#forli72").hide();
		$("#forli73").hide();
		$("#forli71").hide();
		$("#forli75").hide();
	});
	$("#li75").click(function()
	{
		$("#forli75").toggle();
		$("#forli72").hide();
		$("#forli73").hide();
		$("#forli74").hide();
		$("#forli71").hide();
	});
	$("#li8").click(function()
	{
	   $("#forli8").show();
	   $("#forvis").css("padding", "0px");
	   $("#forvis").css("visibility", "hidden");
	    $("#forli1").hide();
	    $("#forli3").hide();
		 $("#forli4").hide();
		  $("#forli2").hide();
		  $("#forli6").hide();
	    $("#forli7").hide();
		 $("#forli5").hide();
		  $("#forli9").hide();
		   $("#forli10").hide();
	});
	$("#li8").dblclick(function()
	{
	   $("#forli8").hide();
	   $("#forvis").css("padding", "200px");
	    $("#forli1").hide();
	    $("#forli3").hide();
		 $("#forli4").hide();
		  $("#forli2").hide();
		  $("#forli6").hide();
	    $("#forli7").hide();
		 $("#forli5").hide();
		  $("#forli9").hide();
		   $("#forli10").hide();
	});
	$("#li9").click(function()
	{
	   $("#forli9").show();
	   $("#forvis").css("padding", "0px");
	   $("#forvis").css("visibility", "hidden");
	    $("#forli1").hide();
	    $("#forli3").hide();
		 $("#forli4").hide();
		  $("#forli2").hide();
		  $("#forli6").hide();
	    $("#forli7").hide();
		 $("#forli8").hide();
		  $("#forli5").hide();
		   $("#forli10").hide();
	});
	$("#li9").dblclick(function()
	{
	   $("#forli9").hide();
	   $("#forvis").css("padding", "200px");
	    $("#forli1").hide();
	    $("#forli3").hide();
		 $("#forli4").hide();
		  $("#forli2").hide();
		  $("#forli6").hide();
	    $("#forli7").hide();
		 $("#forli8").hide();
		  $("#forli5").hide();
		   $("#forli10").hide();
	});
	$("#li10").click(function()
	{
	   $("#forli10").show();
	   $("#forvis").css("padding", "0px");
	   $("#forvis").css("visibility", "hidden");
	    $("#forli1").hide();
	    $("#forli3").hide();
		 $("#forli4").hide();
		  $("#forli2").hide();
		  $("#forli6").hide();
	    $("#forli7").hide();
		 $("#forli8").hide();
		  $("#forli9").hide();
		   $("#forli5").hide();
	});
	$("#li10").dblclick(function()
	{
	   $("#forli9").hide();
	   $("#forvis").css("padding", "200px");
	   
	    $("#forli1").hide();
	    $("#forli3").hide();
		 $("#forli4").hide();
		  $("#forli2").hide();
		  $("#forli6").hide();
	    $("#forli7").hide();
		 $("#forli8").hide();
		  $("#forli10").hide();
		   $("#forli5").hide();
	});
	$("#li711").click(function()
	{
		$("#auth1").toggle();
	});
	$("#li712").click(function()
	{
		$("#auth1").toggle();
	});
	$("#li713").click(function()
	{
		$("#auth1").toggle();
	});
	$("#li714").click(function()
	{
		$("#auth1").toggle();
	});
	$("#li715").click(function()
	{
		$("#auth1").toggle();
	});
	$("#li716").click(function()
	{
		$("#auth1").toggle();
	});
	$("#li721").click(function()
	{
		$("#auth1").toggle();
	});
	$("#li722").click(function()
	{
		$("#auth1").toggle();
	});
	$("#li731").click(function()
	{
		$("#auth1").toggle();
	});
	$("#li732").click(function()
	{
		$("#auth1").toggle();
	});
	$("#li741").click(function()
	{
		$("#auth1").toggle();
	});
	$("#li742").click(function()
	{
		$("#auth1").toggle();
	});
	$("#li751").click(function()
	{
		$("#auth1").toggle();
	});
	$("#li752").click(function()
	{
		$("#auth1").toggle();
	});
	$("#li81").click(function()
	{
		$("#auth2").toggle();
	});
	$("#li82").click(function()
	{
		$("#auth2").toggle();
	});
	$("#li83").click(function()
	{
		$("#auth2").toggle();
	});
	$("#li84").click(function()
	{
		$("#auth2").toggle();
	});
	$("#li85").click(function()
	{
		$("#auth2").toggle();
	});
	$("#sp1").click(function()
	{
		$("#auth3").toggle();
	});
	
	
	
	
	
	
	
});